### PR TITLE
URI: Trim excess "xmpp:" if it was provided

### PR DESCRIPTION
**Pull request by earboxer**
Close https://github.com/ge0rg/easy-xmpp-invitation/issues/37

### CODE REVIEW

**Comment by sjehuda** [comment]
Thank you for taking care of this

**Comment by ge0rg** [comment]
Merged in d172071d02d0a390820841eb83a066e1e2511ba9, thank you very much!

**Comment by sjehuda** [comment]
Zach, do you think we should use URL interface for cases of `xmpp://`?

**Comment by earboxer** [comment]
@sjehuda, as far as I know, there are no invitation XEP's which specify a URI beginning with `xmpp://`.

If there are popular clients/servers which create invitation URIs like this, we may consider it, but I think the first recourse would be to just fix those nonconforming clients/servers.

(maybe the confusion is that #16 shows a regex with `/` as separators, so it looks like a reference to `xmpp://`)

**Comment by sjehuda** [comment]
> I think the first recourse would be to just fix those nonconforming clients/servers.

I agree

**Pull request closed without merging**
