### PR TITLE
Get rid of bootstrap

### PR DESCRIPTION
**Pull request by mdosch**
Should work, but check it first as newly created this branch as I had more changes done in my fork (still learning how to use git ^^).

### CODE REVIEW

**Comment by stevenroose** [comment]
You forgot to remove the actual bootstrap file.

**Comment by ge0rg** [comment]
I have some more modifications and optimizations in the https://github.com/ge0rg/easy-xmpp-invitation/tree/bootstrapless branch in case you are interested.

**Comment by ge0rg** [comment]
Merged into master.

**Pull request closed without merging**
